### ISSUE TITLE
Orchestrator unable to delete flush and replication agents

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-orchestrator#11]
Orchestrator errors with "Method Not Allowed" message when deleting flush and replication agents.

```
2017-03-05 22:33:40 [SessionCallBackSchedulerThread-1] ERROR c.s.a.a.ScaleDownAuthorDispatcherAction - Failed to delete flush agent for dispatcher id: i-04dc42481fe9c8067, and run mode: author
com.shinesolutions.swaggeraem4j.ApiException: Method Not Allowed
	at com.shinesolutions.swaggeraem4j.ApiClient.handleResponse(ApiClient.java:1047)
	at com.shinesolutions.swaggeraem4j.ApiClient.execute(ApiClient.java:970)
	at com.shinesolutions.swaggeraem4j.ApiClient.execute(ApiClient.java:953)
	at com.shinesolutions.swaggeraem4j.api.SlingApi.deleteAgentWithHttpInfo(SlingApi.java:145)
	at com.shinesolutions.aemorchestrator.aem.FlushAgentManager.deleteFlushAgent(FlushAgentManager.java:40)
	at com.shinesolutions.aemorchestrator.aem.FlushAgentManager$$FastClassBySpringCGLIB$$e599d4da.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:122)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.shinesolutions.aemorchestrator.aem.FlushAgentManager$$EnhancerBySpringCGLIB$$581ee12e.deleteFlushAgent(<generated>)
	at com.shinesolutions.aemorchestrator.actions.ScaleDownAuthorDispatcherAction.execute(ScaleDownAuthorDispatcherAction.java:34)
	at com.shinesolutions.aemorchestrator.handler.AutoScalingTerminateEventHandler.handleEvent(AutoScalingTerminateEventHandler.java:31)
	at com.shinesolutions.aemorchestrator.handler.SqsMessageHandler.handleMessage(SqsMessageHandler.java:52)
	at com.shinesolutions.aemorchestrator.service.MessageReceiver.onMessage(MessageReceiver.java:42)
	at com.amazon.sqs.javamessaging.SQSSessionCallbackScheduler.run(SQSSessionCallbackScheduler.java:151)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by nletts** [comment]
Fix required version 0.9.2 of swaggeraem4j
