### ISSUE TITLE
Lack of pairing candidate availability shouldn't cause continual snapshotting

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-orchestrator#12]
When Orchestrator encountered an error during publish layer scaling up, e.g. when it can't find any unpaired publish-dispatcher instance, it currently reprocess the message which causes a snapshot to be created again on each retry.

```
2017-03-07 15:03:28 [SessionCallBackSchedulerThread-1] WARN  c.s.a.actions.ScaleUpPublishAction - Failed to find unpaired publish dispatcher
java.util.NoSuchElementException: No value present
at java.util.Optional.get(Optional.java:135)
at com.shinesolutions.aemorchestrator.service.AemInstanceHelperService.findUnpairedPublishDispatcher(AemInstanceHelperService.java:236)
at com.shinesolutions.aemorchestrator.service.AemInstanceHelperService$$FastClassBySpringCGLIB$$a28d9dcf.invoke(<generated>)
at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
at org.springframework.retry.interceptor.RetryOperationsInterceptor$1.doWithRetry(RetryOperationsInterceptor.java:74)
at org.springframework.retry.support.RetryTemplate.doExecute(RetryTemplate.java:276)
at org.springframework.retry.support.RetryTemplate.execute(RetryTemplate.java:157)
at org.springframework.retry.interceptor.RetryOperationsInterceptor.invoke(RetryOperationsInterceptor.java:101)
at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:119)
at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
at com.shinesolutions.aemorchestrator.service.AemInstanceHelperService$$EnhancerBySpringCGLIB$$b1e78141.findUnpairedPublishDispatcher(<generated>)
at com.shinesolutions.aemorchestrator.actions.ScaleUpPublishAction.execute(ScaleUpPublishAction.java:94)
at com.shinesolutions.aemorchestrator.handler.AutoScalingEventHandler.handleEvent(AutoScalingEventHandler.java:38)
at com.shinesolutions.aemorchestrator.handler.SqsMessageHandler.handleMessage(SqsMessageHandler.java:52)
at com.shinesolutions.aemorchestrator.service.MessageReceiver.onMessage(MessageReceiver.java:42)
at com.amazon.sqs.javamessaging.SQSSessionCallbackScheduler.run(SQSSessionCallbackScheduler.java:151)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Comment by nletts** [comment]
I've changed (and optimised) the ordering of scale up publish tasks, so that snapshotting is performed last. That way if something fails, the snapshot will not be taken.
