### ISSUE TITLE
Error 400 while scaling up publisher

### ISSUE THREAD

**Issue by cliffano** [shinesolutions/aem-orchestrator#5]
This error shows up when recovering from all publish instances being terminated:

```
2017-02-23 17:29:24 [SessionCallBackSchedulerThread-1] ERROR c.s.a.h.AutoScalingEventHandler - Failed to execute autoscaling:EC2_INSTANCE_LAUNCH action for auto scaling group name: stackprefix-aem-publish-stack-PublishAutoScalingGroup-KML9H6V7L7M9
com.amazonaws.services.ec2.model.AmazonEC2Exception: The volume 'vol-03d57d541eb57af5a' is 'creating' (Service: AmazonEC2; Status Code: 400; Error Code: IncorrectState; Request ID: 98cbc9d8-db1e-4e3d-a753-101cdc5c4f8e)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.handleErrorResponse(AmazonHttpClient.java:1586)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeOneRequest(AmazonHttpClient.java:1254)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeHelper(AmazonHttpClient.java:1035)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.doExecute(AmazonHttpClient.java:747)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.executeWithTimer(AmazonHttpClient.java:721)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.execute(AmazonHttpClient.java:704)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutor.access$500(AmazonHttpClient.java:672)
        at com.amazonaws.http.AmazonHttpClient$RequestExecutionBuilderImpl.execute(AmazonHttpClient.java:654)
        at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:518)
        at com.amazonaws.services.ec2.AmazonEC2Client.doInvoke(AmazonEC2Client.java:11840)
        at com.amazonaws.services.ec2.AmazonEC2Client.invoke(AmazonEC2Client.java:11816)
        at com.amazonaws.services.ec2.AmazonEC2Client.createSnapshot(AmazonEC2Client.java:2769)
        at com.shinesolutions.aemorchestrator.service.AwsHelperService.createSnapshot(AwsHelperService.java:209)
        at com.shinesolutions.aemorchestrator.service.AwsHelperService$$FastClassBySpringCGLIB$$e115e7b0.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.retry.annotation.AnnotationAwareRetryOperationsInterceptor.invoke(AnnotationAwareRetryOperationsInterceptor.java:122)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
        at com.shinesolutions.aemorchestrator.service.AwsHelperService$$EnhancerBySpringCGLIB$$c62f753a.createSnapshot(<generated>)
        at com.shinesolutions.aemorchestrator.actions.ScaleUpPublishAction.execute(ScaleUpPublishAction.java:63)
        at com.shinesolutions.aemorchestrator.handler.AutoScalingEventHandler.handleEvent(AutoScalingEventHandler.java:38)
        at com.shinesolutions.aemorchestrator.handler.SqsMessageHandler.handleMessage(SqsMessageHandler.java:52)
        at com.shinesolutions.aemorchestrator.service.MessageReceiver.onMessage(MessageReceiver.java:42)
        at com.amazon.sqs.javamessaging.SQSSessionCallbackScheduler.run(SQSSessionCallbackScheduler.java:151)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by nletts** [comment]
Just re-tested this by terminating all publish instances simultaneously. The error did not appear. It may have been inadvertently fixed with the with the #13 change. Closing for now.
